apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-docusaurus-env
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
data:
  REACT_APP_VERSION: {{ .Values.tag | default .Chart.AppVersion | quote }}
  REACT_APP_DOCS_NEXT_HOST: {{ .Values.env.REACT_APP_DOCS_NEXT_HOST | quote }}
  REACT_APP_DOCS_NEXT_ORG: {{ .Values.env.REACT_APP_DOCS_NEXT_ORG | quote }}
  REACT_APP_TYPESENSE_PROTOCOL: {{ .Values.env.REACT_APP_TYPESENSE_PROTOCOL | quote }}
  REACT_APP_TYPESENSE_HOST: {{ .Values.env.REACT_APP_TYPESENSE_HOST | quote }}
  REACT_APP_TYPESENSE_PORT: {{ .Values.env.REACT_APP_TYPESENSE_PORT | quote }}
  REACT_APP_TYPESENSE_API_KEY: {{ .Values.env.REACT_APP_TYPESENSE_API_KEY | quote }}
  UMAMI_WEBSITE_ID: {{ .Values.env.UMAMI_WEBSITE_ID | quote }}
  UMAMI_ANALYTICS_DOMAIN: {{ .Values.env.UMAMI_ANALYTICS_DOMAIN | quote }}
  UMAMI_DATAHOST_URL: {{ .Values.env.UMAMI_DATAHOST_URL | quote }}
  UMAMI_DATA_DOMAIN: {{ .Values.env.UMAMI_DATA_DOMAIN | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docusaurus
  labels:
    app: docusaurus
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: docusaurus
    {{- include "docusaurus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: docusaurus
      {{- include "docusaurus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: docusaurus
        image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-docusaurus-env
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docusaurus
  labels:
  {{- include "docusaurus.labels" . | nindent 4 }}
spec:
  selector:
    app: docusaurus
  {{- include "docusaurus.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32767
    protocol: TCP
