replicas: 5
image: quay.io/opentelekomcloud/docs-next
tag: v0.0.4
ingress:
  host:
  clusterIssuer: letsencrypt-prod
typesense:
  api-key:
  storage:
    size: 40Gi
    storageClassName: csi-disk
  ingress:
    host:
    clusterIssuer: letsencrypt-prod
  scraper:
    schedule: '*/5 * * * *'