typesense:
  image: typesense/typesense:30.0
  replicas: 3
  apiKey: 
  storage:
    size: 1Gi
    storageClassName: local-path
  scraper:
    collection: docs-next
    schedule: '*/2 * * * *'
    target:
      host: docs-next-docusaurus.docs-next.svc.cluster.local
